### ISSUE TITLE
S3Object#exists? fails when no object

### ISSUE THREAD

**Issue by michalf** [JoshMcKin/em_aws#14]
Hi,

I came across the following bug. Given the config:

```ruby
AWS.config({
  access_key_id: CONFIG.aws.api_key,
  secret_access_key: CONFIG.aws.secret,
  http_handler: AWS::Http::EMHttpHandler.new
})
```

the following fails if and object does NOT exist:

```ruby

AWS::S3.new.buckets[mybucket].objects['this-does-not-exist'].exists?
```
```
AWS::Errors::Base: 
	from /Users/michalf/.rvm/gems/ruby-1.9.3-p327/gems/aws-sdk-1.8.1.3/lib/aws/core/client.rb:318:in `return_or_raise'
	from /Users/michalf/.rvm/gems/ruby-1.9.3-p327/gems/aws-sdk-1.8.1.3/lib/aws/core/client.rb:419:in `client_request'
	from (eval):3:in `head_object'
	from /Users/michalf/.rvm/gems/ruby-1.9.3-p327/gems/aws-sdk-1.8.1.3/lib/aws/s3/s3_object.rb:294:in `head'
	from /Users/michalf/.rvm/gems/ruby-1.9.3-p327/gems/aws-sdk-1.8.1.3/lib/aws/s3/s3_object.rb:271:in `exists?'
	from (irb):5
	from /Users/michalf/.rvm/rubies/ruby-1.9.3-p327/bin/irb:16:in `<main>'
```

I have not yet time to look into this, but this seems critical to our project. It works with the default HTTP handler.

Thanks in advance!
Michal

**Comment by JoshMcKin** [comment]
Does not appear to be an error anymore.
